all:
  children:
    proxmox_nodes:
      hosts:
        amdpve:
        pve:
        zimaboard:

    media_nodes:
      hosts:
        media-ct01:

    monitoring_nodes:
      hosts:
        monitor01:

    security_nodes:
      hosts:
        wazuh-mgr01:
        sensor01:
