all:
  children:
    proxmox_nodes:
      hosts:
        amdpve:
        pve:
        zimaboard:

    media_nodes:
      hosts:
        media-ct01:
          ansible_host: 10.0.60.10
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3

    monitoring_nodes:
      hosts:
        monitor01:
          ansible_host: 10.0.50.10

    security_nodes:
      hosts:
        wazuh-mgr01:
          ansible_host: 10.0.50.20
        sensor01:
          ansible_host: 10.0.50.30

