---
media_puid: 1000
media_pgid: 1000
media_tz: America/Chicago

media_root: /srv/stacks/media
media_config_dir: "{{ media_root }}/config"
media_media_dir: "{{ media_root }}/media"
media_downloads_dir: "{{ media_root }}/downloads"

qbittorrent_web_port: 8080
sabnzbd_web_port: 8081

# Wireguard secrets â€“ you can move these into Vault later
wireguard_private_key: "{{ vault_wireguard_private_key }}"
wireguard_address: "{{ vault_wireguard_address }}"
wireguard_dns: "{{ vault_wireguard_dns }}"
wireguard_preshared_key: "{{ vault_wireguard_preshared_key }}"
wireguard_endpoint_ip: "{{ vault_wireguard_endpoint_ip }}"
wireguard_endpoint_port: "{{ vault_wireguard_endpoint_port }}"
